_target_: epochalyst.model.ModelPipeline
_convert_: partial

x_sys:
  _target_: src.modules.transformation.verbose_transformation_pipeline.VerboseTransformationPipeline
  title: "Preprocessing pipeline"

y_sys:
  _target_: src.modules.transformation.verbose_transformation_pipeline.VerboseTransformationPipeline
  title: "Label processing pipeline"

train_sys:
  _target_: src.modules.training.verbose_training_pipeline.VerboseTrainingPipeline

pred_sys:
  _target_: src.modules.transformation.verbose_transformation_pipeline.VerboseTransformationPipeline
  title: "Postprocessing pipeline"

label_sys:
  _target_: src.modules.transformation.verbose_transformation_pipeline.VerboseTransformationPipeline
