defaults:
  - pipeline/default@_here_
  - _self_

x_sys:

y_sys:

train_sys:
  steps:
    - _target_: src.modules.training.main_trainer.MainTrainer
      model_name: MultiResidualBiGRU # Can't have special characters or spaces
      two_stage: true
      # two_stage_kl_threshold: 5.5
      two_stage_evaluator_threshold: 9
      two_stage_split_test: true
      two_stage_pretrain_full: true
      test_split_type: 10
      model:
        _target_: src.modules.training.models.parkinson_multi_res_bi_gru.MultiResidualBiGRU
        input_size: 72
        hidden_size: 64
        out_size: 6
        n_layers: 2
      optimizer: # Partially instantiate optimizer, so model parameters can be linked at runtime
        _target_: functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: torch.optim.AdamW
        lr: 0.00315
      criterion:
        _target_: src.modules.training.losses.kldiv_logits.CustomKLDivLogitsLoss
        reduction: "batchmean"
      epochs: 50
      batch_size: 64
      patience: 15
      scheduler:
        _target_: functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: timm.scheduler.cosine_lr.CosineLRScheduler
        t_initial: 50
        cycle_mul: 1
        cycle_decay: 1
        cycle_limit: 1
        warmup_t: 5
        warmup_lr_init: 1e-5
    - _target_: src.modules.training.postprocessing.softmax.Softmax

