defaults:
  - base_train
  - hydra/logging
  - model: ??? # Add models or ensembles
  - wandb: train

###############
#             #
#    PATHS    #
#             #
###############

scorer:
  _target_: ??? # Add scorer
splitter:
  _target_: ??? # Add splitter
  n_splits: 10
allow_multiple_instances: true
