defaults:
  - base_train
  - hydra/logging
  - model: mlp # Add models or ensembles
  - wandb: train

###############
#             #
#    PATHS    #
#             #
###############
processed_path: data/processed
raw_path: data/raw
cache_path: data/cache
data_path: data/raw/train_data/iris.csv

splitter:
  _target_: sklearn.model_selection.KFold
  n_splits: 2 # Set to 0 if you want train full.
  shuffle: false

scorer:
  _target_: src.scoring.accuracy.Accuracy
  name: accuracy

allow_multiple_instances: true
