name: Static Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "v*" ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12.3
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
